name: 'Check formatting'
on:
  push:
jobs:
  check_formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.1.3
      - run: pnpm install
      - run: pnpm run format:check
